bit_gateway:
  - set_id: di
    set_size: 112
    item_type: sensor
    modbus_read_address: 0
  - set_id: meter
    set_size: 8
    item_type: sensor
    modbus_read_address: 112
  - set_id: do
    set_size: 152
    item_type: binary_light
    modbus_read_address: 512
    modbus_write_address: 0