
MQTT_AVAILABILITY_TOPIC = "plc/availability"

MQTT_SERVER_HOST = "192.168.210.7"
MQTT_CLIENT_NAME = "modbus-gateway"

MQTT_USERNAME = "mosquitto-modbus-gw"
MQTT_PASSWORD = "YVz4Bcqen2sZaL"

DISCOVERY_PREFIX = "homeassistant"

MODBUS_SERVER_HOST = "192.168.210.22"
MODBUS_SERVER_PORT = 502
